name: Build Game
on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Actualizamos a la 22 para evitar avisos de depreciación

      - name: Install dependencies
        # EL CAMBIO CLAVE: Forzamos la instalación ignorando conflictos de peer deps
        run: npm install --legacy-peer-deps

      - name: Build Web App
        # CI: false ignora warnings de código que podrían detener el build
        run: npm run build
        env:
          CI: false

      - name: Build Electron App
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.os }}
          path: dist_electron/*.*
