name: Build Game Executables
on: [push] # Se ejecuta cada vez que subes algo

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # Crea versiones para Windows y Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Build Electron Executable
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || 'linux' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-executable-${{ matrix.os }}
          path: dist_electron/*.exe # Para Windows
          # path: dist_electron/*.AppImage # Para Linux
